import mockImageGotic from '../../assets/img/mock-image-moment.png'
export const dataMockMemories = [
    {memoryTitle:"A gótica foda",
     memoryDescription:"Ontem fui pra Liberdade só pra ver como era, parecia mais uma roda de macumba, uns caras batucando uns tambores esquisitos e umas velas no meio da calçada, e aí do nada eu vi ela, parada num canto como se tivesse sido invocada ali mesmo, toda de preto, coturno alto, maquiagem preta borrada e um olhar que parecia que ela via o além, juro que até os pombos desviavam dela, fiquei olhando porque era impossível não olhar, parecia saída de um filme estranho que passa de madrugada, e o pior é que ela me encarou de volta, tipo com desprezo e interesse ao mesmo tempo, daí eu gelei, não sabia se era medo ou paixão, mas continuei andando fingindo costume, e por dentro só pensava “meu Deus, será que ela escuta Evanescence e faz feitiço na garagem?”, e eu não sei por quê, mas desde então eu fico voltando lá todo fim de semana, só pra ver se encontro de novo a gótica foda." , 
     memoryImage:mockImageGotic,
     memoryIconName:"Love",
     memoryLocalDate:'22/03/2025',
     memoryLocalHour:'22:32',
   //caio<- DADOS mockados com as infos da gótica 
    },
    {memoryTitle:"A gótica foda",
        memoryDescription:"Ontem fui pra Liberdade só pra ver como era, parecia mais uma roda de macumba, uns caras batucando uns tambores esquisitos e umas velas no meio da calçada, e aí do nada eu vi ela, parada num canto como se tivesse sido invocada ali mesmo, toda de preto, coturno alto, maquiagem preta borrada e um olhar que parecia que ela via o além, juro que até os pombos desviavam dela, fiquei olhando porque era impossível não olhar, parecia saída de um filme estranho que passa de madrugada, e o pior é que ela me encarou de volta, tipo com desprezo e interesse ao mesmo tempo, daí eu gelei, não sabia se era medo ou paixão, mas continuei andando fingindo costume, e por dentro só pensava “meu Deus, será que ela escuta Evanescence e faz feitiço na garagem?”, e eu não sei por quê, mas desde então eu fico voltando lá todo fim de semana, só pra ver se encontro de novo a gótica foda." , 
        memoryImage:null,
        memoryIconName:"Love",
        memoryLocalDate:'22/03/2025',
        memoryLocalHour:'22:32',
      //caio<- DADOS mockados com as infos da gótica 
       },
       {memoryTitle:"A gótica foda",
        memoryDescription:"Ontem fui pra Liberdade só pra ver como era, parecia mais uma roda de macumba, uns caras batucando uns tambores esquisitos e umas velas no meio da calçada, e aí do nada eu vi ela, parada num canto como se tivesse sido invocada ali mesmo, toda de preto, coturno alto, maquiagem preta borrada e um olhar que parecia que ela via o além, juro que até os pombos desviavam dela, fiquei olhando porque era impossível não olhar, parecia saída de um filme estranho que passa de madrugada, e o pior é que ela me encarou de volta, tipo com desprezo e interesse ao mesmo tempo, daí eu gelei, não sabia se era medo ou paixão, mas continuei andando fingindo costume, e por dentro só pensava “meu Deus, será que ela escuta Evanescence e faz feitiço na garagem?”, e eu não sei por quê, mas desde então eu fico voltando lá todo fim de semana, só pra ver se encontro de novo a gótica foda." , 
        memoryImage:mockImageGotic,
        memoryIconName:"Love",
        memoryLocalDate:'22/03/2025',
        memoryLocalHour:'22:32',
      //caio<- DADOS mockados com as infos da gótica 
       },
       {memoryTitle:"A gótica foda",
        memoryDescription:"Ontem fui pra Liberdade só pra ver como era, parecia mais uma roda de macumba, uns caras batucando uns tambores esquisitos e umas velas no meio da calçada, e aí do nada eu vi ela, parada num canto como se tivesse sido invocada ali mesmo, toda de preto, coturno alto, maquiagem preta borrada e um olhar que parecia que ela via o além, juro que até os pombos desviavam dela, fiquei olhando porque era impossível não olhar, parecia saída de um filme estranho que passa de madrugada, e o pior é que ela me encarou de volta, tipo com desprezo e interesse ao mesmo tempo, daí eu gelei, não sabia se era medo ou paixão, mas continuei andando fingindo costume, e por dentro só pensava “meu Deus, será que ela escuta Evanescence e faz feitiço na garagem?”, e eu não sei por quê, mas desde então eu fico voltando lá todo fim de semana, só pra ver se encontro de novo a gótica foda." , 
        memoryImage:mockImageGotic,
        memoryIconName:"Love",
        memoryLocalDate:'22/03/2025',
        memoryLocalHour:'22:32',
      //caio<- DADOS mockados com as infos da gótica 
       },
       {memoryTitle:"A gótica foda",
        memoryDescription:"Ontem fui pra Liberdade só pra ver como era, parecia mais uma roda de macumba, uns caras batucando uns tambores esquisitos e umas velas no meio da calçada, e aí do nada eu vi ela, parada num canto como se tivesse sido invocada ali mesmo, toda de preto, coturno alto, maquiagem preta borrada e um olhar que parecia que ela via o além, juro que até os pombos desviavam dela, fiquei olhando porque era impossível não olhar, parecia saída de um filme estranho que passa de madrugada, e o pior é que ela me encarou de volta, tipo com desprezo e interesse ao mesmo tempo, daí eu gelei, não sabia se era medo ou paixão, mas continuei andando fingindo costume, e por dentro só pensava “meu Deus, será que ela escuta Evanescence e faz feitiço na garagem?”, e eu não sei por quê, mas desde então eu fico voltando lá todo fim de semana, só pra ver se encontro de novo a gótica foda." , 
        memoryImage:mockImageGotic,
        memoryIconName:"Love",
        memoryLocalDate:'22/03/2025',
        memoryLocalHour:'22:32',
      //caio<- DADOS mockados com as infos da gótica 
       },
       {memoryTitle:"A gótica foda",
        memoryDescription:"Ontem fui pra Liberdade só pra ver como era, parecia mais uma roda de macumba, uns caras batucando uns tambores esquisitos e umas velas no meio da calçada, e aí do nada eu vi ela, parada num canto como se tivesse sido invocada ali mesmo, toda de preto, coturno alto, maquiagem preta borrada e um olhar que parecia que ela via o além, juro que até os pombos desviavam dela, fiquei olhando porque era impossível não olhar, parecia saída de um filme estranho que passa de madrugada, e o pior é que ela me encarou de volta, tipo com desprezo e interesse ao mesmo tempo, daí eu gelei, não sabia se era medo ou paixão, mas continuei andando fingindo costume, e por dentro só pensava “meu Deus, será que ela escuta Evanescence e faz feitiço na garagem?”, e eu não sei por quê, mas desde então eu fico voltando lá todo fim de semana, só pra ver se encontro de novo a gótica foda." , 
        memoryImage:mockImageGotic,
        memoryIconName:"Love",
        memoryLocalDate:'22/03/2025',
        memoryLocalHour:'22:32',
      //caio<- DADOS mockados com as infos da gótica 
       },
       {memoryTitle:"A gótica foda",
        memoryDescription:"Ontem fui pra Liberdade só pra ver como era, parecia mais uma roda de macumba, uns caras batucando uns tambores esquisitos e umas velas no meio da calçada, e aí do nada eu vi ela, parada num canto como se tivesse sido invocada ali mesmo, toda de preto, coturno alto, maquiagem preta borrada e um olhar que parecia que ela via o além, juro que até os pombos desviavam dela, fiquei olhando porque era impossível não olhar, parecia saída de um filme estranho que passa de madrugada, e o pior é que ela me encarou de volta, tipo com desprezo e interesse ao mesmo tempo, daí eu gelei, não sabia se era medo ou paixão, mas continuei andando fingindo costume, e por dentro só pensava “meu Deus, será que ela escuta Evanescence e faz feitiço na garagem?”, e eu não sei por quê, mas desde então eu fico voltando lá todo fim de semana, só pra ver se encontro de novo a gótica foda." , 
        memoryImage:mockImageGotic,
        memoryIconName:"Love",
        memoryLocalDate:'22/03/2025',
        memoryLocalHour:'22:32',
      //caio<- DADOS mockados com as infos da gótica 
       },
       {memoryTitle:"A gótica foda",
        memoryDescription:"Ontem fui pra Liberdade só pra ver como era, parecia mais uma roda de macumba, uns caras batucando uns tambores esquisitos e umas velas no meio da calçada, e aí do nada eu vi ela, parada num canto como se tivesse sido invocada ali mesmo, toda de preto, coturno alto, maquiagem preta borrada e um olhar que parecia que ela via o além, juro que até os pombos desviavam dela, fiquei olhando porque era impossível não olhar, parecia saída de um filme estranho que passa de madrugada, e o pior é que ela me encarou de volta, tipo com desprezo e interesse ao mesmo tempo, daí eu gelei, não sabia se era medo ou paixão, mas continuei andando fingindo costume, e por dentro só pensava “meu Deus, será que ela escuta Evanescence e faz feitiço na garagem?”, e eu não sei por quê, mas desde então eu fico voltando lá todo fim de semana, só pra ver se encontro de novo a gótica foda." , 
        memoryImage:mockImageGotic,
        memoryIconName:"Love",
        memoryLocalDate:'22/03/2025',
        memoryLocalHour:'22:32',
      //caio<- DADOS mockados com as infos da gótica 
       },
       {memoryTitle:"A gótica foda",
        memoryDescription:"Ontem fui pra Liberdade só pra ver como era, parecia mais uma roda de macumba, uns caras batucando uns tambores esquisitos e umas velas no meio da calçada, e aí do nada eu vi ela, parada num canto como se tivesse sido invocada ali mesmo, toda de preto, coturno alto, maquiagem preta borrada e um olhar que parecia que ela via o além, juro que até os pombos desviavam dela, fiquei olhando porque era impossível não olhar, parecia saída de um filme estranho que passa de madrugada, e o pior é que ela me encarou de volta, tipo com desprezo e interesse ao mesmo tempo, daí eu gelei, não sabia se era medo ou paixão, mas continuei andando fingindo costume, e por dentro só pensava “meu Deus, será que ela escuta Evanescence e faz feitiço na garagem?”, e eu não sei por quê, mas desde então eu fico voltando lá todo fim de semana, só pra ver se encontro de novo a gótica foda." , 
        memoryImage:mockImageGotic,
        memoryIconName:"Love",
        memoryLocalDate:'22/03/2025',
        memoryLocalHour:'22:32',
      //caio<- DADOS mockados com as infos da gótica 
       },
       {memoryTitle:"A gótica foda",
        memoryDescription:"Ontem fui pra Liberdade só pra ver como era, parecia mais uma roda de macumba, uns caras batucando uns tambores esquisitos e umas velas no meio da calçada, e aí do nada eu vi ela, parada num canto como se tivesse sido invocada ali mesmo, toda de preto, coturno alto, maquiagem preta borrada e um olhar que parecia que ela via o além, juro que até os pombos desviavam dela, fiquei olhando porque era impossível não olhar, parecia saída de um filme estranho que passa de madrugada, e o pior é que ela me encarou de volta, tipo com desprezo e interesse ao mesmo tempo, daí eu gelei, não sabia se era medo ou paixão, mas continuei andando fingindo costume, e por dentro só pensava “meu Deus, será que ela escuta Evanescence e faz feitiço na garagem?”, e eu não sei por quê, mas desde então eu fico voltando lá todo fim de semana, só pra ver se encontro de novo a gótica foda." , 
        memoryImage:mockImageGotic,
        memoryIconName:"Love",
        memoryLocalDate:'22/03/2025',
        memoryLocalHour:'22:32',
      //caio<- DADOS mockados com as infos da gótica 
       },
       {memoryTitle:"A gótica foda",
        memoryDescription:"Ontem fui pra Liberdade só pra ver como era, parecia mais uma roda de macumba, uns caras batucando uns tambores esquisitos e umas velas no meio da calçada, e aí do nada eu vi ela, parada num canto como se tivesse sido invocada ali mesmo, toda de preto, coturno alto, maquiagem preta borrada e um olhar que parecia que ela via o além, juro que até os pombos desviavam dela, fiquei olhando porque era impossível não olhar, parecia saída de um filme estranho que passa de madrugada, e o pior é que ela me encarou de volta, tipo com desprezo e interesse ao mesmo tempo, daí eu gelei, não sabia se era medo ou paixão, mas continuei andando fingindo costume, e por dentro só pensava “meu Deus, será que ela escuta Evanescence e faz feitiço na garagem?”, e eu não sei por quê, mas desde então eu fico voltando lá todo fim de semana, só pra ver se encontro de novo a gótica foda." , 
        memoryImage:mockImageGotic,
        memoryIconName:"Love",
        memoryLocalDate:'22/03/2025',
        memoryLocalHour:'22:32',
      //caio<- DADOS mockados com as infos da gótica 
       }]